### ISSUE TITLE
ValueError: could not convert string to float: 

### ISSUE THREAD

**Issue by soichih** [kitchell/app-binvolvolume#1]
I tested this App using Freesurfer from HCP3T/100206 and generatetract/masks output from HCP3T derivative. 

It failed with following error message.

```
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/mnt/share1/prod/5b2e6d8a93c6a50048c7c105/5b2e6d8a93c6a50048c7c108/main.py", line 23, in <module>
    icv = float(lines[34][84:98]) 
ValueError: could not convert string to float: 
```

I haven't investigated the issue at all, but just FYI

**Comment by kitchell** [comment]
hm, I ran it fine on all the UCLA data, must have to do with the format of the HCP freesurfer data

**Comment by kitchell** [comment]
The way I am parsing the aseg.stats file is not great:

asegstatsfile = open(config["fsurfer"]+"/stats/aseg.stats", 'r')
lines =  asegstatsfile.readlines()
icv = float(lines[34][84:98]) 

The lines are probably not consistent with the HCP freesurfer output

**Comment by kitchell** [comment]
nice, I should have searched a bit more for a function like that, I did not know 'startswith' existed.
